name: 'ci-go'
on:
  pull_request:
    branches:
    - 'main'
jobs:
  test:
    permissions:
      id-token: 'write'
      contents: 'read'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 1
    - name: 'Set up Go'
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: 'go.mod'
        check-latest: true
    - name: 'Check Go modules'
      run: |
        make tidy
        if [[ ! -z "$(git status --short)" ]]
        then
          echo "there are some modified files, rerun 'make tidy' to update them and check the changes in"
          git status
          exit 1
        fi
    - name: 'Test'
      run: make test
  lint:
    permissions:
      contents: 'read'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 1
    - name: 'Set up Go'
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: 'go.mod'
        check-latest: true
    - name: 'Check Go modules'
      run: |
        make lint