name: Verify

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0
      - name: Set up Golang
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "1.24.1"
          check-latest: true
      - name: 'Check Go modules'
        run: |
          make tidy
          if [[ ! -z "$(git status --short)" ]]
          then
            echo "there are some modified files, rerun 'make tidy' to update them and check the changes in"
            git status
            exit 1
          fi          
      - name: Lint
        run: make lint
      - name: Test 
        run: make test
